---
- name: Testing andrewrothstein.sshkey (1)
  hosts: all
  tasks:
    - name: Mkdir test1
      ansible.builtin.file:
        path: /tmp/test1
        state: directory
        mode: '755'
    - name: Testing andrewrothstein.sshkey (1)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        sshkey_pki_dir: '{{ playbook_dir }}/test-pki'
        sshkey_target_dir: /tmp/test1
- name: Testing andrewrothstein.sshkey (2)
  hosts: all
  tasks:
    - name: Mkdir test2
      ansible.builtin.file:
        path: /tmp/test2
        state: directory
        mode: '755'
    - name: Testing andrewrothstein.sshkey (2)
      ansible.builtin.include_role:
        name: '{{ playbook_dir }}'
      vars:
        sshkey_pki_dir: '{{ playbook_dir }}/test-pki'
        sshkey_target_dir: /tmp/test2
        sshkey_target_perms:
          owner: root
          group: root
        sshkey_override_target_cert: cert.pem
        sshkey_override_target_key: key.pem
